Brotli micronaut controller custom header
Tesco/aqueduct-core pull request #289
Opened 2020-09-08 12:41 UTC by LorenzoCianciaruso

2020-09-08 14:00 UTC, ashish-sharma09 commented on pipe-http-server/src/integration/groovy/com/tesco/aqueduct/pipe/http/PipeReadControllerIntegrationSpec.groovy
> +    private RestAssuredConfig config = RestAssured.config().decoderConfig(DecoderConfig.decoderConfig().contentDecoders(DecoderConfig.ContentDecoder.DEFLATE))
Why do we need this, is RestAssured not doing gzip decoding by default?

2020-09-08 14:04 UTC, ashish-sharma09 commented on pipe-http-server/src/main/java/com/tesco/aqueduct/pipe/http/PipeReadController.java
> +    @Property(name="compression.threshold")
The default value for this can be specified as 1024 or something, then we do not have to specify in all integration tests explicitly where applicable.

2020-09-08 14:06 UTC, ashish-sharma09 commented on registry-http-server/src/main/java/com/tesco/aqueduct/registry/http/NodeRegistryControllerV2.java
> +                    .header(HttpHeaders.CONTENT_ENCODING, "gzip");
formatting

2020-09-08 14:08 UTC, ashish-sharma09 commented on pipe-http-server/src/integration/groovy/com/tesco/aqueduct/pipe/http/PipeReadControllerIntegrationSpec.groovy
> +                            .get("/pipe/0?location=someLocation")
formatting

2020-09-08 14:09 UTC, ashish-sharma09 commented on pipe-http-server/src/integration/groovy/com/tesco/aqueduct/pipe/http/PipeReadControllerIntegrationSpec.groovy
> +                        .get("/pipe/0?location=someLocation")
formatting

2020-09-08 14:39 UTC, sebastianlavender commented on pipe-http-server/src/main/java/com/tesco/aqueduct/pipe/http/PipeReadController.java
> +    @Property(name="compression.threshold")
I think that having it just in the application.yml file means that if it needs changing it only needs to be done in one place. Having to specify it across different tests seems to be a fair trade off and similar to what we have done with other properties.

2020-09-08 14:42 UTC, sebastianlavender commented on pipe-http-server/src/integration/groovy/com/tesco/aqueduct/pipe/http/PipeReadControllerIntegrationSpec.groovy
> +    private RestAssuredConfig config = RestAssured.config().decoderConfig(DecoderConfig.decoderConfig().contentDecoders(DecoderConfig.ContentDecoder.DEFLATE))
removed as not needed now due to size limit on compressing data

2020-09-08 14:49 UTC, adam-yorwerth commented on pipe-http-server/src/main/java/com/tesco/aqueduct/pipe/http/PipeReadController.java
> +    @Property(name="compression.threshold")
Using @Value with a default is a way to do this

2020-09-08 14:55 UTC, sebastianlavender commented on pipe-http-server/src/main/java/com/tesco/aqueduct/pipe/http/PipeReadController.java
> +    @Property(name="compression.threshold")
True but this config is used in both the PipeReadContoller and the NodeRegistryController

2020-09-08 15:13 UTC, ashish-sharma09 submitted a review, later dismissed
LGTM

2020-09-08 15:21 UTC, KrzysztofKowalczyk commented on build.gradle
> +                testImplementation('com.nixxcode.jvmbrotli:jvmbrotli:0.2.0') {
This opening bracket on this line worries me a bit, it is meant for exclusions etc,

2020-09-08 15:21 UTC, KrzysztofKowalczyk commented on pipe-api/src/main/java/com/tesco/aqueduct/pipe/api/HttpHeaders.java
> +    public static final String X_CONTENT_ENCODING = "X-Content-Encoding";
X header? why?

2020-09-08 15:25 UTC, sebastianlavender commented on pipe-api/src/main/java/com/tesco/aqueduct/pipe/api/HttpHeaders.java
> +    public static final String X_CONTENT_ENCODING = "X-Content-Encoding";
Apigee doesn't support any content-encoding except gzip. So to allow brotli to be used we need to use an X_CONTENT_ENCODING header

2020-09-08 15:27 UTC, sebastianlavender commented on build.gradle
> +                testImplementation('com.nixxcode.jvmbrotli:jvmbrotli:0.2.0') {
This done for the addMicronautDependencies so this follows the same pattern, which I believe you wrote?

2020-09-08 15:32 UTC, KrzysztofKowalczyk commented on pipe-codec/src/main/java/com/tesco/aqueduct/pipe/codec/BrotliCodec.java
> +        this.parameters = new Encoder.Parameters().setQuality(4);
why not to use this(4)

2020-09-08 15:34 UTC, KrzysztofKowalczyk requested changes
Info logs for millions of requests  x 3 x 2600 ?

2020-09-08 15:35 UTC, KrzysztofKowalczyk commented on pipe-codec/src/main/java/com/tesco/aqueduct/pipe/codec/BrotliCodec.java
> +        LOG.info("pre-encode:size", String.valueOf(input.length));
that's an info log, without a fence on every single http request done by this service

2020-09-08 15:37 UTC, KrzysztofKowalczyk commented on pipe-codec/src/test/groovy/com/tesco/aqueduct/pipe/codec/BrotliCodecSpec.groovy
> +class BrotliCodecSpec extends Specification {
this tests does not test if anything is actually compressed

2020-09-08 15:39 UTC, KrzysztofKowalczyk commented on pipe-http-server-cloud/src/integration/groovy/com/tesco/aqueduct/pipe/CodecIntegrationSpec.groovy
> +                "compression.threshold":                        1024
a lot of settings for a test

2020-09-08 15:41 UTC, KrzysztofKowalczyk commented on pipe-http-server-cloud/src/integration/groovy/com/tesco/aqueduct/pipe/CodecIntegrationSpec.groovy
> +    }
Whole database setup for a single integration test? Well, ok, but not put here from scratch, don't we have this code somewhere already? Share it in test fixture or other way?

2020-09-08 15:41 UTC, KrzysztofKowalczyk commented on pipe-http-server-cloud/src/integration/groovy/com/tesco/aqueduct/pipe/CodecIntegrationSpec.groovy
> +    }
even full mock for integration test?

2020-09-08 15:46 UTC, KrzysztofKowalczyk commented on pipe-http-server/src/main/java/com/tesco/aqueduct/pipe/http/PipeReadController.java
> +        }
why?

2020-09-08 15:46 UTC, KrzysztofKowalczyk commented on pipe-http-server/src/main/java/com/tesco/aqueduct/pipe/http/PipeReadController.java
> +        }
Too long method

2020-09-08 15:49 UTC, sebastianlavender commented on pipe-codec/src/main/java/com/tesco/aqueduct/pipe/codec/BrotliCodec.java
> +        LOG.info("pre-encode:size", String.valueOf(input.length));
agreed we need to remove some of the logging

2020-09-09 06:52 UTC, adam-yorwerth commented on pipe-codec/src/main/java/com/tesco/aqueduct/pipe/codec/BrotliCodec.java
> +        LOG.info("pre-encode:size", String.valueOf(input.length));
I think we should remove the ratio log (as this can be calculated), but leave the pre/post encode ones in for now.

We can also trade in removing some excess existing logs for these being added.

2020-09-09 07:58 UTC, sebastianlavender commented on pipe-codec/src/test/groovy/com/tesco/aqueduct/pipe/codec/BrotliCodecSpec.groovy
> +class BrotliCodecSpec extends Specification {
Added test

2020-09-09 09:51 UTC, adam-yorwerth commented on pipe-http-server-cloud/configuration/application.yml
> +compression.threshold: 1024
Can we give this units in the name?

2020-09-09 09:55 UTC, adam-yorwerth commented on pipe-http-server/src/main/java/com/tesco/aqueduct/pipe/http/PipeReadController.java
> +        }
Agreed, this should be extracted

2020-09-09 11:24 UTC, KrzysztofKowalczyk submitted a review, later dismissed
unblocking

2020-09-09 14:46 UTC, adam-yorwerth approved these changes

2020-09-09 14:53 UTC, ashish-sharma09 approved these changes
LGTM

2020-09-09 15:14 UTC, merged