Use retry in ms header
Tesco/aqueduct-core pull request #317
Opened 2020-10-15 10:17 UTC by sebastianlavender

2020-10-15 10:39 UTC, LorenzoCianciaruso commented on pipe-api/src/main/java/com/tesco/aqueduct/pipe/api/HttpHeaders.java
> +    public static final String RETRY_AFTER_MS = "Retry-After-Ms";
I wonder, and this might be a refactoring card, if we should move to X-headers for all our custom header, now it's a bit of a mixed bag

2020-10-15 10:41 UTC, sebastianlavender commented on pipe-api/src/main/java/com/tesco/aqueduct/pipe/api/HttpHeaders.java
> +    public static final String RETRY_AFTER_MS = "Retry-After-Ms";
I think this makes sense that we should do this for all the headers. But to keep PR's simple we should do this in another PR

2020-10-15 11:23 UTC, LorenzoCianciaruso commented on pipe-http-client/src/main/java/com/tesco/aqueduct/pipe/http/client/HttpPipeClient.java
> +                .orElse(0L));
I know this was here already, by defaulting to 0L if no header is set is dangerous I think, it would allow all the tills to immediately call the pipe regardless. We should set it to the current mac retry I think

2020-10-15 11:24 UTC, LorenzoCianciaruso commented on pipe-http-client/src/main/java/com/tesco/aqueduct/pipe/http/client/HttpPipeClient.java
> +            return 0L;
same as above

2020-10-15 11:26 UTC, LorenzoCianciaruso commented on pipe-http-client/src/main/java/com/tesco/aqueduct/pipe/http/client/HttpPipeClient.java
> +            return 0L;
Do we need to catch the exception here btw? I wonder if we should just let it check the Retry-After header instead

2020-10-15 11:27 UTC, LorenzoCianciaruso commented on pipe-http-client/src/test/groovy/com/tesco/aqueduct/pipe/http/client/HttpPipeClientSpec.groovy
> +        "foo" | "bar"   | 0
same as above on the retry-after 0 in case of error, not sure if we want that

2020-10-15 11:38 UTC, LorenzoCianciaruso commented on pipe-http-server/src/main/java/com/tesco/aqueduct/pipe/http/PipeReadController.java
> +        responseHeaders.put(HttpHeaders.RETRY_AFTER_MS, String.valueOf(retryTime));
I've probably missed it but, do we have a test that ensure both headers are present?

2020-10-15 11:38 UTC, LorenzoCianciaruso commented on pipe-http-server/src/main/java/com/tesco/aqueduct/pipe/http/PipeReadController.java
> +        responseHeaders.put(HttpHeaders.RETRY_AFTER_MS, String.valueOf(retryTime));
Ignore, found it

2020-10-15 11:44 UTC, LorenzoCianciaruso commented on pipe-http-server/src/main/java/com/tesco/aqueduct/pipe/http/PipeReadController.java
> +        final long retryAfterSeconds = (long) Math.ceil(retryTime / (double) 1000);
one it's called retryAfterSeconds and the other retryTime, personally I find it confusing. Maybe we should just have retryAfterMs and then inline the retryAfter in seconds in the following line. Or just rename the vars consistently

2020-10-15 11:45 UTC, LorenzoCianciaruso requested changes
I think it's good overall, just some comments here and there

2020-10-15 12:16 UTC, sebastianlavender commented on pipe-http-client/src/main/java/com/tesco/aqueduct/pipe/http/client/HttpPipeClient.java
> +                .orElse(0L));
yeah that makes sense and this was discussed yesterday, I'll amend to use the maximum retry after

2020-10-15 12:17 UTC, sebastianlavender commented on pipe-http-client/src/main/java/com/tesco/aqueduct/pipe/http/client/HttpPipeClient.java
> +            return 0L;
This needs to catch the number format exception unless we are 100% confident that the retry-after header will give back a value that can be parsed into a long.

On the other point I agree this should use the maximum value for retry

2020-10-15 12:52 UTC, ashish-sharma09 commented on pipe-http-client/src/main/java/com/tesco/aqueduct/pipe/http/client/HttpPipeClient.java
> +                .orElse(0L));
The repeating code here can potentially be extracted for reuse and simplicity, something like follows:
```
private Long extractHeaderOrElse(HttpHeader header, Supplier<Long> elseSupplier) {
          Optional
                .ofNullable(response.header(header))
                .map(this::checkForValidNumber)
                .map(value -> Long.max(0, value * 1000))
                .orElse(elseSupplier.get())
}
```
and then invoking it something as:

``` 
extractHeaderOrElse(HttpHeaders.RETRY_AFTER_MS, () -> extractHeaderOrElse(HttpHeaders.RETRY_AFTER, () -> 0L))
```

2020-10-15 13:59 UTC, sebastianlavender commented on pipe-http-client/src/main/java/com/tesco/aqueduct/pipe/http/client/HttpPipeClient.java
> +                .orElse(0L));
I'm going to leave as is as I think it will be easier to refactor and remove the code once we no longer need retry after in seconds

2020-10-15 14:00 UTC, sebastianlavender commented on pipe-http-server/src/main/java/com/tesco/aqueduct/pipe/http/PipeReadController.java
> +        final long retryAfterSeconds = (long) Math.ceil(retryTime / (double) 1000);
renamed

2020-10-15 14:11 UTC, LorenzoCianciaruso approved these changes

2020-10-16 13:41 UTC, ashish-sharma09 approved these changes
LGTM

2020-10-16 13:53 UTC, merged