Ignore deleted messages when calculating offset consistency sum
Tesco/aqueduct-core pull request #363
Opened 2021-03-23 16:39 UTC by ashish-sharma09

* Adjust consistency sum to ignore delete messages

2021-03-23 16:42 UTC, adam-yorwerth requested changes
Let's not merge this yet - need to have a bit of time with consistency first

2021-05-17 09:26 UTC, adam-yorwerth approved these changes

2021-05-17 09:46 UTC, ashish-sharma09 commented on pipe-storage-sqlite/src/integration/groovy/com/tesco/aqueduct/pipe/storage/sqlite/SQLiteStorageIntegrationSpec.groovy
> +    def 'calculateOffsetConsistencySum counts offset of a message that has multiple deletes including the latest one'() {
this should say something like: "calculateOffsetConsistencySum ignores offset of a message that has multiple deletes"

2021-05-17 09:50 UTC, LorenzoCianciaruso submitted a review, later dismissed

2021-05-17 10:41 UTC, LorenzoCianciaruso approved these changes

2021-05-17 10:54 UTC, merged